/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-05-27 21:16:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class my_0020item_0020view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Yashmika%20Anusara/OneDrive/Documents/SLIIT%20Assignments%20&%20Projects/(2nd%20Year%201st%20Semester)%20SLIIT%20Assignment%20&%20Project/Group%20Project/OOP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Shopping/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1621331815794L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/myitemview.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("<script src=\"js/myitemview.js\"></script>\r\n");
      out.write("<title>Online Grocery Store</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("    <nav>\r\n");
      out.write("		<label class=\"logo\">GroceryPro</label>\r\n");
      out.write("		<ul>\r\n");
      out.write("		   <li><a class=\"active\" href=\"sellerhome.jsp\">Home</a></li>\r\n");
      out.write("		   <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("		   <li><a href=\"my items.jsp\">My Items</a></li>\r\n");
      out.write("		   <li>\r\n");
      out.write("			<a href=\"#\">My Account\r\n");
      out.write("				<i class=\"fas fa-caret-down\"></i>\r\n");
      out.write("			</a>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"additems.jsp\">Add Items</a></li>\r\n");
      out.write("				<li><a href=\"profile.jsp\">Profile</a></li>\r\n");
      out.write("				<li><a href=\"login.jsp\">Log Out</a></li>\r\n");
      out.write("				<li>\r\n");
      out.write("			</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li><a href=\"#\">Feedback</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	 </nav>\r\n");
      out.write("</header>\r\n");
      out.write("<table>     \r\n");
      out.write(" <tr>\r\n");
      out.write(" 	 <th>Item ID</th>\r\n");
      out.write("	 <th>Item Picture</th>\r\n");
      out.write("	 <th>Item Name</th>\r\n");
      out.write("	 <th>Item Quantity</th>\r\n");
      out.write("	 <th>Item Price</th>\r\n");
      out.write("	 <th></th>\r\n");
      out.write("</tr>      \r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<footer class=\"footer\" style=\"margin-top: 180px;\">\r\n");
      out.write("  	 <div class=\"container\">\r\n");
      out.write("  	 	<div class=\"row\">\r\n");
      out.write("  	 		<div class=\"footer-col\">\r\n");
      out.write("  	 		<h4>company</h4>\r\n");
      out.write("  	 		<ul>\r\n");
      out.write("  	 				<li><a href=\"#\">our services</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">privacy policy</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">affiliate program</a></li>\r\n");
      out.write("  	 			</ul>\r\n");
      out.write("  	 		</div>\r\n");
      out.write("  	 		<div class=\"footer-col\">\r\n");
      out.write("  	 			<h4>get help</h4>\r\n");
      out.write("  	 			<ul>\r\n");
      out.write("  	 				<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">shipping</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">returns</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">order status</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">payment options</a></li>\r\n");
      out.write("  	 			</ul>\r\n");
      out.write("  	 		</div>\r\n");
      out.write("  	 		<div class=\"footer-col\">\r\n");
      out.write("  	 			<h4>online shop</h4>\r\n");
      out.write("  	 			<ul>\r\n");
      out.write("  	 				<li><a href=\"#\">watch</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">bag</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">shoes</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">dress</a></li>\r\n");
      out.write("  	 			</ul>\r\n");
      out.write("  	 		</div>\r\n");
      out.write("  	 		<div class=\"footer-col\">\r\n");
      out.write("  	 			<h4>About us</h4>\r\n");
      out.write("  	 				<p class=\"par\">Welcome to Sri Lanka's first inspirational global experience in online grocery retailing. Be a part of this experience, redefining convenience and freshness.</p>\r\n");
      out.write("  	 			</div>\r\n");
      out.write("  	 		</div>\r\n");
      out.write("  	 	</div>\r\n");
      out.write("  </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /my item view.jsp(48,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/my item view.jsp(48,0) '${item}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${item}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /my item view.jsp(48,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("  \r\n");
            out.write(" <tr>	\r\n");
            out.write(" 		<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write(" 		<td><img src=\"images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.pic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" width=\"150px\" height=\"150px\" ></td>\r\n");
            out.write("		<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("		<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("		<td>Rs.");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("		<td><button onclick=\"page()\">Delete</button></td>\r\n");
            out.write("</tr>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
